# -*- coding: utf-8 -*-
"""Ánh xạ thủ công Organization -> quốc gia trụ sở.

Đây là trụ sở tổ chức, không phải vị trí người học hoặc nơi khóa học được tiêu
thụ. Các ánh xạ cần được dẫn nguồn trong báo cáo trước khi nộp chính thức.
"""

ORG_COUNTRY_MAP = {
    "Google": "United States",
    "University of Michigan": "United States",
    "IBM": "United States",
    "University of Pennsylvania": "United States",
    "Yale University": "United States",
    "Johns Hopkins University": "United States",
    "DeepLearning.AI": "United States",
    "University of California, Irvine": "United States",
    "Duke University": "United States",
    "Stanford University": "United States",
    "Google Cloud": "United States",
    "University of Illinois Urbana-Champaign": "United States",
    "Georgia Institute of Technology": "United States",
    "University of California, Davis": "United States",
    "University of California San Diego": "United States",
    "University of Colorado Boulder": "United States",
    "Meta": "United States",
    "University of Virginia": "United States",
    "University of London": "United Kingdom",
    "Macquarie University": "Australia",
    "California Institute of the Arts": "United States",
    "University of Washington": "United States",
    "Rice University": "United States",
    "University of Minnesota": "United States",
    "The University of Edinburgh": "United Kingdom",
    "Yonsei University": "South Korea",
    "University of Toronto": "Canada",
    "Microsoft": "United States",
    "University of Colorado System": "United States",
    "Wesleyan University": "United States",
    "University of Alberta": "Canada",
    "Imperial College London": "United Kingdom",
    "Peking University": "China",
    "Michigan State University": "United States",
    "Vanderbilt University": "United States",
    "The Museum of Modern Art": "United States",
    "The Hong Kong University of Science and Technology": "Hong Kong",
    "Berklee": "United States",
    "Arizona State University": "United States",
    "The State University of New York": "United States",
    "The University of Sydney": "Australia",
    "University of California, Santa Cruz": "United States",
    "Rutgers the State University of New Jersey": "United States",
    "Kennesaw State University": "United States",
    "Amazon Web Services": "United States",
    "University at Buffalo": "United States",
    "University of Amsterdam": "Netherlands",
    "Universiteit Leiden": "Netherlands",
    "University of Geneva": "Switzerland",
    "Università Bocconi": "Italy",
    "École Polytechnique Fédérale de Lausanne": "Switzerland",
    "Columbia University": "United States",
    "IE Business School": "Spain",
    "Northwestern University": "United States",
    "Erasmus University Rotterdam": "Netherlands",
    "University of Maryland, College Park": "United States",
    "Emory University": "United States",
    "Indian School of Business": "India",
    "The University of North Carolina at Chapel Hill": "United States",
    "University of Copenhagen": "Denmark",
    "PwC": "United Kingdom",
    "Lund University": "Sweden",
    "Ludwig-Maximilians-Universität München (LMU)": "Germany",
    "McMaster University": "Canada",
    "Copenhagen Business School": "Denmark",
    "Technical University of Denmark (DTU)": "Denmark",
    "The University of Chicago": "United States",
    "University of Florida": "United States",
    "University of Cape Town": "South Africa",
    "Intuit": "United States",
    "Korea Advanced Institute of Science and Technology(KAIST)": "South Korea",
    "Case Western Reserve University": "United States",
    "UNSW Sydney (The University of New South Wales)": "Australia",
    "SAS": "United States",
    "IESE Business School": "Spain",
    "Princeton University": "United States",
    "Atlassian": "Australia",
    "ESSEC Business School": "France",
    "New York University": "United States",
    "Tel Aviv University": "Israel",
    "The University of Tokyo": "Japan",
    "Hebrew University of Jerusalem": "Israel",
    "Shanghai Jiao Tong University": "China",
    "Pontificia Universidad Católica de Chile": "Chile",
    "École Polytechnique": "France",
    "University of Rochester": "United States",
    "University of Manchester": "United Kingdom",
    "University of Arizona": "United States",
    "The University of Melbourne": "Australia",
    "IIMA - IIM Ahmedabad": "India",
    "Universitat Autònoma de Barcelona": "Spain",
    "National Taiwan University": "Taiwan",
    "EIT Digital": "Belgium",
    "Salesforce": "United States",
    "University of Kentucky": "United States",
    "INSEAD": "France",
    "American Museum of Natural History": "United States",
    "University of Pittsburgh": "United States",
    "Eindhoven University of Technology": "Netherlands",
    "University of Houston": "United States",
    "Icahn School of Medicine at Mount Sinai": "United States",
    "Infosec": "United States",
    "Universitat de Barcelona": "Spain",
    "The Pennsylvania State University": "United States",
    "SAP": "Germany",
    "Utrecht University": "Netherlands",
    "HRCI": "United States",
    "West Virginia University": "United States",
    "Board Infinity": "India",
    "Tsinghua University": "China",
    "EDHEC Business School": "France",
    "Nanjing University": "China",
    "University of New Mexico": "United States",
    "Nanyang Technological University, Singapore": "Singapore",
    "CertNexus": "United States",
    "Caltech": "United States",
    "The Linux Foundation": "United States",
    "Relay Graduate School of Education": "United States",
    "New York Institute of Finance": "United States",
    "National University of Singapore": "Singapore",
    "MathWorks": "United States",
    "Politecnico di Milano": "Italy",
    "Sungkyunkwan University": "South Korea",
    "The Chinese University of Hong Kong": "Hong Kong",
    "The University of Hong Kong": "Hong Kong",
    "University of Leeds": "United Kingdom",
    "ISC2": "United States",
    "Interactive Brokers": "United States",
    "Sciences Po": "France",
    "Digital Marketing Institute": "Ireland",
    "MedCerts": "United States",
    "University of Zurich": "Switzerland",
    "Google AR & VR": "United States",
    "Technion - Israel Institute of Technology": "Israel",
    "École des Ponts ParisTech": "France",
    "Cloudera": "United States",
    "University of Western Australia": "Australia",
    "JetBrains": "Czech Republic",
    "HEC Paris": "France",
    "EC-Council": "United States",
    "Osmosis": "United States",
    # --- Mở rộng top 151-298 (nâng độ phủ từ 81.7% lên 100%) ---
    "Curtis Institute of Music": "United States",
    "Dartmouth College": "United States",
    "Technical University of Munich (TUM)": "Germany",
    "Cisco Learning and Certifications": "United States",
    "Scrimba": "Norway",
    "Pohang University of Science and Technology(POSTECH)": "South Korea",
    "High Tech High Graduate School of Education": "United States",
    "ConsenSys Academy": "United States",
    "HubSpot Academy": "United States",
    "Advancing Women in Tech": "United States",
    "Università di Napoli Federico II": "Italy",
    "The George Washington University": "United States",
    "University of Glasgow": "United Kingdom",
    "SoFi": "United States",
    "GitLab": "United States",
    "University of North Texas": "United States",
    "Universidad Nacional Autónoma de México": "Mexico",
    "Edge Impulse": "United States",
    "Palo Alto Networks": "United States",
    "Alberta Machine Intelligence Institute": "Canada",
    "Northeastern University": "United States",
    "Sapienza University of Rome": "Italy",
    "Unilever": "United Kingdom",
    "Fractal Analytics": "United States",
    "L&T EduTech": "India",
    "Red Hat": "United States",
    "Queen Mary University of London": "United Kingdom",
    "University of Lausanne": "Switzerland",
    "UiPath": "United States",
    "National Academy of Sports Medicine": "United States",
    "VMware": "United States",
    "NVIDIA": "United States",
    "Intel": "United States",
    "Illinois Tech": "United States",
    "Tally Education and Distribution Services Private Limited": "India",
    "Voxy": "United States",
    "ISAE-SUPAERO": "France",
    "Siemens": "Germany",
    "Keller Williams": "United States",
    "EDUCBA": "India",
    "École normale supérieure": "France",
    "Fundação Instituto de Administração": "Brazil",
    "Akamai Technologies, Inc.": "United States",
    "Goodwill Industries International": "United States",
    "Qualcomm Academy": "United States",
    "Whizlabs": "India",
    "Measure What Matters": "United States",
    "The World Bank Group": "United States",
    "Oracle": "United States",
    "Novartis": "Switzerland",
    "Brightline Initiative": "United States",
    "O.P. Jindal Global University": "India",
    "Automatic Data Processing, Inc. (ADP)": "United States",
    "Olay": "United States",
    "HPE Aruba Networking": "United States",
    "Institute for the Future": "United States",
    "Exploratorium": "United States",
    "Workday": "United States",
    "Association of International Certified Professional Accountants": "United States",
    "MongoDB Inc.": "United States",
    "Institut Mines-Télécom": "France",
    "CVS Health": "United States",
    "Edureka": "India",
    "Howard University": "United States",
    "Splunk Inc.": "United States",
    "Birla Institute of Technology & Science, Pilani": "India",
    "Arm": "United Kingdom",
    "Coursera": "United States",
    "American Psychological Association": "United States",
    "ESCP Business School": "France",
    "Big Interview": "United States",
    "New Teacher Center": "United States",
    "LearnKartS": "India",
    "Karlsruhe Institute of Technology": "Germany",
    "Autodesk": "United States",
    "Indian Institute for Human Settlements": "India",
    "United Cities and Local Governments of Africa": "Morocco",
    "Carnegie Mellon University": "United States",
    "Epic Games": "United States",
    "Yad Vashem": "Israel",
    "Tecnológico de Monterrey": "Mexico",
    "Databricks": "United States",
    "Alibaba Cloud Academy": "China",
    "Yeshiva University": "United States",
    "Universidad Austral": "Argentina",
    "Amazon": "United States",
    "King Abdullah University of Science and Technology": "Saudi Arabia",
    "Khalifa University": "United Arab Emirates",
    "Campus BBVA": "Spain",
    "Xi'an Jiaotong University": "China",
    "Snowflake": "United States",
    "Corporate Finance Institute": "Canada",
    "University of Virginia Darden School Foundation": "United States",
    "Adobe": "United States",
    "Talend": "France",
    "Parsons School of Design, The New School": "United States",
    "PwC India": "India",
    "London Business School": "United Kingdom",
    "Automation Anywhere": "United States",
    "NIIT": "India",
    "University of Nebraska": "United States",
    "Indian Institute of Technology Guwahati": "India",
    "Fortinet, Inc.": "United States",
    "Blue Prism": "United Kingdom",
    "Universidad Autónoma Metropolitana": "Mexico",
    "Google - Spectrum Sharing": "United States",
    "GRAMMY GO": "United States",
    "Ball State University": "United States",
    "Moderna": "United States",
    "Capitals Coalition": "Netherlands",
    "The University of Notre Dame": "United States",
    "Fred Hutchinson Cancer Center": "United States",
    "Universidade de São Paulo": "Brazil",
    "Tufts University": "United States",
    "USO": "United States",
    "Check Point Software Technologies Ltd.": "Israel",
    "IIT Bombay": "India",
    "Tencent Cloud": "China",
    "Genentech": "United States",
    "Royal Holloway, University of London": "United Kingdom",
    "Morehouse College": "United States",
    "Organization not found": "UNKNOWN",  # placeholder gốc, đã chuyển Organization -> NaN ở bước 01
    "Amazon Ads": "United States",
    "University of California, Berkeley": "United States",
    "Banco Interamericano de Desarrollo": "United States",
    "American Council on Exercise": "United States",
    "PepsiCo": "United States",
    "S.P. Jain Institute of Management and Research": "India",
    "Packt": "United Kingdom",
    "Juniper Networks": "United States",
    "Indian Institute of Science": "India",
    "Samsung": "South Korea",
    "SAE Institute México": "Mexico",
    "IIT Roorkee": "India",
    "FAIR Institute": "United States",
    "Liberty Mutual Insurance": "United States",
    "Tinder": "United States",
    "Enviolo": "Netherlands",
    "ISACA": "United States",
    "Coursera Project Network": "United States",
    "Dell": "United States",
    "IMD - International Institute for Management Development": "Switzerland",
    "Universidad de los Andes": "Colombia",
    "Universidad Peruana de Ciencias Aplicadas": "Peru",
    "Universidad de Palermo": "Argentina",

    # --- Bổ sung 12 tổ chức còn thiếu (399 dòng) ---
    "Coursera Instructor Network": "United States",   # Mạng giảng viên nội bộ Coursera (US)
    "LearnQuest": "United States",                    # Công ty đào tạo IT, trụ sở Massachusetts
    "SkillUp EdTech": "India",                        # Startup EdTech, trụ sở Bangalore
    "Starweaver": "United States",                    # Nền tảng đào tạo doanh nghiệp, trụ sở New York
    "Codio": "United Kingdom",                        # Nền tảng lập trình cloud, trụ sở London
    "Commonwealth Education Trust": "United Kingdom", # Quỹ giáo dục, trụ sở London
    "Tableau Learning Partner": "United States",      # Đối tác đào tạo Tableau (Salesforce - US)
    "Deep Teaching Solutions": "Canada",              # Công ty ML/AI, trụ sở Alberta
    "KodeKloud": "India",                             # Nền tảng DevOps, trụ sở Hyderabad
    "Knowledge Accelerators": "United States",        # Công ty đào tạo IT, trụ sở US
    "Aptly": "United States",                         # Nền tảng đào tạo sản phẩm, trụ sở US
    "ROI Training": "United States",                  # Công ty đào tạo IT, trụ sở California
}
